export type ToolSlug =
  | "qr-code-generator"
  | "percentage-calculator"
  | "age-calculator"
  | "json-formatter"
  | "password-generator"
  | "image-resizer"
  | "text-case-converter"
  | "username-generator"
  | "color-picker-tool"
  | "time-zone-converter"
  | "random-number-generator"
  | "random-word-generator"
  | "lorem-ipsum-generator"
  | "color-palette-generator"
  | "font-generator-tool"
  | "hashtag-generator"
  | "slogan-generator"
  | "business-name-generator"
  | "email-generator"
  | "uuid-generator"
  | "barcode-generator"
  | "word-cloud-generator"
  | "title-generator"
  | "acronym-generator"
  | "ascii-art-generator"
  | "plot-generator"
  | "anagram-generator"
  | "phone-number-generator"
  | "random-letter-generator"
  | "random-animal-generator"
  | "random-city-generator"
  | "random-country-generator"
  | "fantasy-name-generator"
  | "superhero-name-generator"
  | "fake-data-generator"
  | "secret-santa-generator"
  | "bingo-card-generator"
  | "truth-table-generator"
  | "rhyming-word-generator"
  | "color-scheme-generator"
  | "headline-generator"
  | "thesis-statement-generator"
  | "restaurant-name-generator"
  | "fancy-text-generator"
  | "glitch-text-generator"
  | "mla-citation-generator"
  | "business-niche-generator"
  | "product-name-generator"
  | "startup-idea-generator"
  | "story-prompt-generator"
  | "plot-twist-generator"
  | "word-mixer-generator"
  | "sequence-generator"
  | "icon-label-generator"
  | "character-name-generator"
  | "team-name-generator"
  | "ai-prompt-starter-generator"
  | "tagline-generator";

export type ToolFAQ = { q: string; a: string };

export type ToolConfig = {
  slug: ToolSlug;
  h1: string;
  title: string;
  description: string;
  keyword: string;
  intro: string;
  howTo: string[];
  useCases: string[];
  whyUseful: string[];
  faqs: ToolFAQ[];
  related: ToolSlug[];
};

export const TOOL_CONFIGS: ToolConfig[] = [
  {
    slug: "qr-code-generator",
    h1: "QR Code Generator",
    title: "QR Code Generator Free",
    description:
      "Generate QR codes for text, URLs, and WiFi credentials with a fast QR code generator free for everyday sharing.",
    keyword: "wifi qr code generator",
    intro:
      "Use this wifi qr code generator to create a qr code generator free workflow for links, messages, and network logins. It is built for fast sharing, clean scanning, and simple exports so you can generate qr code images without friction.",
    howTo: [
      "Pick the content type: plain text, URL, or WiFi credentials.",
      "Enter the value you want to encode, then verify the live preview.",
      "Download the PNG and reuse it in posters, handouts, or landing pages.",
    ],
    useCases: [
      "Share a website link at events, on packaging, or in email signatures.",
      "Create a WiFi QR code for guests so they can connect without typing a password.",
      "Add a scannable shortcut to a menu, product sheet, or support page.",
    ],
    whyUseful: [
      "A QR code generator keeps offline and online touchpoints connected, which helps people move from a physical surface to a digital action in one scan.",
      "If you want to build tools like this, you can use kloner.app to launch apps faster and create your own tools with a fast, minimal stack.",
      "You can also build tools like this with kloner.app without shipping a heavy interface or extra setup steps.",
    ],
    faqs: [
      {
        q: "Is this QR code generator free to use?",
        a: "Yes. This page is designed as a simple QR code generator free for quick text, URL, and WiFi exports.",
      },
      {
        q: "Can I create a WiFi QR code generator result for guests?",
        a: "Yes. Enter the SSID, password, and security type to generate a QR code that can be scanned by most phones.",
      },
      {
        q: "What file format do I download?",
        a: "The tool exports a PNG so you can place it in documents, websites, or print layouts without extra conversion.",
      },
    ],
    related: ["json-formatter", "text-case-converter", "color-picker-tool"],
  },
  {
    slug: "percentage-calculator",
    h1: "Percentage Calculator",
    title: "Percentage Difference Calculator",
    description:
      "Calculate percentage change, percentage difference, and reverse percentage with a simple percentage calculator.",
    keyword: "percentage difference calculator",
    intro:
      "This percentage difference calculator helps you compare two values, work out a percentage change calculator result, and see the reverse percentage calculation in one place. It is useful when you want a fast answer without spreadsheet formulas.",
    howTo: [
      "Enter the starting number and the ending number.",
      "Review the change, difference, and reverse percentage results.",
      "Use the outputs for pricing, analytics, or planning notes.",
    ],
    useCases: [
      "Compare product price changes across promotions or sales campaigns.",
      "Check traffic, revenue, or conversion movement from one period to the next.",
      "Measure how far a current value sits from a target value.",
    ],
    whyUseful: [
      "A percentage calculator removes the mental math from decisions that happen quickly, especially when you are comparing many values.",
      "The reverse percentage calculator output is helpful when you know the final number and need to reason backward from it.",
      "If you want to build tools like this, you can use kloner.app to create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "What is the difference between percentage change and percentage difference?",
        a: "Percentage change compares a new value against an old value, while percentage difference compares two values against their average.",
      },
      {
        q: "Can this work as a reverse percentage calculator?",
        a: "Yes. The tool shows the reverse direction as well, so you can read the move from either value.",
      },
      {
        q: "Is this useful for pricing analysis?",
        a: "Yes. It is commonly used for discounts, markups, and any workflow where you need quick percentage math.",
      },
    ],
    related: ["age-calculator", "json-formatter", "username-generator"],
  },
  {
    slug: "age-calculator",
    h1: "Age Calculator",
    title: "Exact Age Calculator",
    description:
      "Find your exact age in years, months, and days with an age calculator from DOB that works instantly in the browser.",
    keyword: "age calculator from dob",
    intro:
      "Use this exact age calculator to compute age in years, months, and days from a date of birth. It is a practical age calculator from dob for forms, records, onboarding, and simple personal checks.",
    howTo: [
      "Choose a date of birth from the calendar input.",
      "Read the exact age output in years, months, and days.",
      "Use it when you need an exact age calculator for a quick answer.",
    ],
    useCases: [
      "Check eligibility for sign-ups, age-restricted services, or school forms.",
      "Calculate exact milestones for birthdays, anniversaries, and personal tracking.",
      "Confirm the current age of customers, members, or event attendees.",
    ],
    whyUseful: [
      "Exact age is often needed when a simple year-only answer is not enough, especially for legal, onboarding, or scheduling workflows.",
      "The calculator avoids off-by-one mistakes by using the current date and precise calendar logic.",
      "If you want to build tools like this, kloner.app helps you create your own tools without adding a heavy build process.",
    ],
    faqs: [
      {
        q: "Does this age calculator use today as the reference date?",
        a: "Yes. It calculates age from the selected date of birth against the current date in your browser.",
      },
      {
        q: "Can I use it as an exact age calculator for forms?",
        a: "Yes. It returns the exact age in years, months, and days, which is useful when year-only results are too broad.",
      },
      {
        q: "Will it work for future birth dates?",
        a: "The interface is intended for valid birth dates, and it will show a helpful message when the date is not usable.",
      },
    ],
    related: ["percentage-calculator", "time-zone-converter", "json-formatter"],
  },
  {
    slug: "json-formatter",
    h1: "JSON Formatter",
    title: "JSON Formatter Tool",
    description:
      "Format raw JSON into readable output with a JSON formatter, JSON beautifier, and JSON pretty print workflow.",
    keyword: "json beautifier",
    intro:
      "This json formatter turns raw data into a clean readable structure. Use it as a json beautifier or json pretty print helper when you need to inspect, share, or copy nested data quickly.",
    howTo: [
      "Paste raw JSON into the input field.",
      "Review the formatted output and correct any syntax errors.",
      "Copy the pretty-printed JSON when you are ready to use it.",
    ],
    useCases: [
      "Debug API responses while building frontends or integrations.",
      "Clean up configuration files before sharing them with teammates.",
      "Inspect webhook payloads, analytics events, or test fixtures.",
    ],
    whyUseful: [
      "Readable JSON reduces mistakes because key names, nesting, and arrays are easier to scan when whitespace is normalized.",
      "A JSON formatter also makes code reviews and support debugging faster when teams need to compare payloads.",
      "If you want to build tools like this, you can use kloner.app to create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Is this a JSON prettify tool or a formatter?",
        a: "It works as both a JSON formatter and a JSON beautifier because it validates and re-indents the same input.",
      },
      {
        q: "Can I use this for JSON pretty print output?",
        a: "Yes. The output is pretty printed with indentation so it is easier to read and paste into other tools.",
      },
      {
        q: "What happens if the JSON is invalid?",
        a: "The tool shows the parse error instead of returning a broken formatted block.",
      },
    ],
    related: ["password-generator", "text-case-converter", "color-picker-tool"],
  },
  {
    slug: "password-generator",
    h1: "Password Generator",
    title: "Strong Password Generator",
    description:
      "Create a strong password generator output with adjustable length, symbols, and numbers for secure sign-ups.",
    keyword: "secure password generator",
    intro:
      "Use this random password generator when you need a secure password generator for accounts, staging credentials, or quick secrets. It is built to create strong combinations without making the interface complicated.",
    howTo: [
      "Set the password length and choose whether to include numbers and symbols.",
      "Generate a password and copy it when the result looks right.",
      "Regenerate until you find a strong password generator result that fits your policy.",
    ],
    useCases: [
      "Create new login credentials for internal tools or demos.",
      "Generate unique passwords for temporary accounts or client handoffs.",
      "Build a strong starting point before saving the password in a manager.",
    ],
    whyUseful: [
      "A secure password generator saves time and reduces the chance that people reuse weak patterns across services.",
      "Random generation is much safer than inventing memorable words when you need high-entropy credentials.",
      "If you want to build tools like this, kloner.app can help you create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Is this a random password generator?",
        a: "Yes. The output is generated with browser crypto APIs so the password is unpredictable.",
      },
      {
        q: "Can I make it stronger by adding symbols and numbers?",
        a: "Yes. Those options increase character variety and help meet common password policies.",
      },
      {
        q: "Should I save the password in the browser?",
        a: "No. Store it in a password manager or your team workflow rather than leaving it visible in the page.",
      },
    ],
    related: ["json-formatter", "username-generator", "color-picker-tool"],
  },
  {
    slug: "image-resizer",
    h1: "Image Resizer",
    title: "Resize Image Online",
    description:
      "Resize image online, compress image output, and download a smaller file with an image resizer free in the browser.",
    keyword: "resize image online",
    intro:
      "Use this image resizer free tool when you need to resize image online and compress it for web delivery. It is designed for quick uploads, sensible defaults, and a lightweight workflow that keeps output under control.",
    howTo: [
      "Upload an image from your device.",
      "Set the target width, height, format, and quality.",
      "Generate the resized file and download it when the preview looks right.",
    ],
    useCases: [
      "Prepare images for blog posts, landing pages, or product galleries.",
      "Compress screenshots before sending them in support conversations.",
      "Convert oversized photos into faster-loading assets for web use.",
    ],
    whyUseful: [
      "A smaller image usually loads faster and is easier to embed in emails, docs, and websites.",
      "Resizing before upload helps reduce bandwidth and keeps page performance in a healthier place.",
      "If you want to build tools like this, you can use kloner.app to create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Does this resize image online without uploading to a server?",
        a: "Yes. The processing happens in the browser, so the workflow stays fast and local.",
      },
      {
        q: "Is this also a compress image tool?",
        a: "Yes. The format and quality controls let you reduce file size while keeping the dimensions you need.",
      },
      {
        q: "Can I keep the aspect ratio?",
        a: "Yes. The resizer maintains the aspect ratio so images do not look stretched or distorted.",
      },
    ],
    related: ["color-picker-tool", "qr-code-generator", "text-case-converter"],
  },
  {
    slug: "text-case-converter",
    h1: "Text Case Converter",
    title: "Uppercase Lowercase Converter",
    description:
      "Convert text instantly with an uppercase lowercase converter, case converter, and text case converter workflow.",
    keyword: "case converter",
    intro:
      "This uppercase lowercase converter helps you switch text formats quickly. Use it as a case converter for titles, labels, snippets, or any text that needs a different presentation style.",
    howTo: [
      "Paste or type the text you want to change.",
      "Choose uppercase, lowercase, or capitalized output.",
      "Copy the version you need and continue writing.",
    ],
    useCases: [
      "Normalize headings, labels, or button text in a design system.",
      "Convert notes or pasted text into a different case style.",
      "Standardize content before publishing it into a CMS or document.",
    ],
    whyUseful: [
      "Text casing is a small detail that affects consistency, and a converter removes the tedious manual edits.",
      "It is especially useful when you are cleaning up copied content from spreadsheets, forms, or external sources.",
      "If you want to build tools like this, kloner.app gives you a faster path to create your own tools.",
    ],
    faqs: [
      {
        q: "Is this a text case converter for titles too?",
        a: "Yes. The capitalized option is useful for headings, while the uppercase and lowercase options handle simpler transformations.",
      },
      {
        q: "Can I use it as an uppercase lowercase converter?",
        a: "Yes. Those two modes are built into the page and update the result instantly.",
      },
      {
        q: "Does the converter preserve spaces?",
        a: "Yes. It changes letter casing while leaving spacing and punctuation intact.",
      },
    ],
    related: ["json-formatter", "username-generator", "password-generator"],
  },
  {
    slug: "username-generator",
    h1: "Username Generator",
    title: "Username Generator Tool",
    description:
      "Generate creative handles with a username generator, cool username generator, and random username generator workflow.",
    keyword: "random username generator",
    intro:
      "This username generator is made for fast brainstorming. Use the cool username generator settings to create random username generator ideas for gaming, social profiles, or product demos.",
    howTo: [
      "Add an optional keyword, nickname, or theme.",
      "Choose the style, number of results, and whether to include numbers.",
      "Generate several username ideas and copy the one that fits best.",
    ],
    useCases: [
      "Brainstorm a new handle for social media or gaming platforms.",
      "Find a placeholder username while testing sign-up forms or dashboards.",
      "Create a brandable account name for early-stage product demos.",
    ],
    whyUseful: [
      "A good username generator saves time when obvious handles are already taken.",
      "Randomized variations help you explore more creative options than a single manual idea.",
      "If you want to build tools like this, you can use kloner.app to create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Does this work as a cool username generator?",
        a: "Yes. The style presets are designed to produce cleaner and more memorable handles.",
      },
      {
        q: "Can I get random username generator results with numbers?",
        a: "Yes. You can toggle numbers on or off depending on the style you want.",
      },
      {
        q: "Is this useful for brand names too?",
        a: "It is mainly a username tool, but the output can also spark short brandable names for side projects.",
      },
    ],
    related: ["password-generator", "color-picker-tool", "time-zone-converter"],
  },
  {
    slug: "color-picker-tool",
    h1: "Color Picker Tool",
    title: "Hex Color Picker",
    description:
      "Pick colors visually, convert RGB to hex, and use a color picker online for quick design work.",
    keyword: "hex color picker",
    intro:
      "This hex color picker makes it easy to pick colors visually and convert RGB to hex values without leaving the page. It is a practical color picker online for design tokens, UI testing, and quick palette checks.",
    howTo: [
      "Choose a color using the picker or adjust the RGB fields.",
      "Copy the HEX or RGB value you need.",
      "Use the live swatch to compare colors before applying them.",
    ],
    useCases: [
      "Match a brand color for UI components, buttons, or backgrounds.",
      "Convert a design reference from RGB to hex for CSS or Tailwind work.",
      "Test accent colors against white backgrounds before shipping a page.",
    ],
    whyUseful: [
      "A color picker online helps teams move faster because the color value is visible in both visual and code-friendly forms.",
      "Hex and RGB conversion is a small but common task in web design, so a dedicated tool keeps the workflow simple.",
      "If you want to build tools like this, kloner.app can help you create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Can this convert RGB to hex?",
        a: "Yes. The RGB fields stay in sync with the HEX value so you can move between formats quickly.",
      },
      {
        q: "Is this a hex color picker for designers?",
        a: "Yes. It is useful for UI work, theme selection, and quick palette validation.",
      },
      {
        q: "Can I use the picked color in CSS?",
        a: "Yes. The HEX and RGB outputs can be pasted directly into CSS variables or component styles.",
      },
    ],
    related: ["image-resizer", "text-case-converter", "qr-code-generator"],
  },
  {
    slug: "time-zone-converter",
    h1: "Time Zone Converter",
    title: "World Time Converter",
    description:
      "Convert time between cities with a time zone converter, world time converter, and timezone converter tool.",
    keyword: "time zone converter",
    intro:
      "Use this timezone converter tool to compare times across cities and regions. It works as a world time converter for calls, launches, meetings, and planning across time zones.",
    howTo: [
      "Choose the source city or time zone and enter the local date and time.",
      "Pick the destination city or time zone.",
      "Convert the time and use the output to plan a call or event.",
    ],
    useCases: [
      "Schedule remote meetings with teammates or clients in different regions.",
      "Check launch timing for announcements, support coverage, or events.",
      "Compare working hours before sending a message to another market.",
    ],
    whyUseful: [
      "A time zone converter reduces back-and-forth by showing the converted time immediately.",
      "It is especially useful for distributed teams that need a fast answer without checking a calendar app.",
      "If you want to build tools like this, you can use kloner.app to create your own tools and launch apps faster.",
    ],
    faqs: [
      {
        q: "Is this a world time converter for meetings?",
        a: "Yes. It helps you translate one local time into another zone so scheduling is easier.",
      },
      {
        q: "Can I convert between city names?",
        a: "Yes. The picker uses common city labels that map to real IANA time zones.",
      },
      {
        q: "Does the timezone converter tool handle daylight saving time?",
        a: "It uses the browser's internationalization APIs, which account for the zone rules in the selected region.",
      },
    ],
    related: ["age-calculator", "qr-code-generator", "percentage-calculator"],
  },
  {
    slug: "random-number-generator",
    h1: "Random Number Generator",
    title: "Random Number Generator Tool",
    description: "Generate a quick set of random numbers within any range.",
    keyword: "random number generator",
    intro: "Use this random number generator when you need a fast set of numbers for picks, tests, or simple decisions.",
    howTo: ["Set the minimum and maximum values.", "Choose how many numbers you need.", "Generate and copy the list you want."],
    useCases: ["Pick winners for a small giveaway.", "Create sample values for testing.", "Fill in placeholders quickly."],
    whyUseful: ["It removes manual number picking when you need a fast answer.", "The output is easy to copy into notes, forms, or spreadsheets.", "It keeps the workflow short and direct."],
    faqs: [
      { q: "Can I change the range?", a: "Yes. Set any minimum and maximum values you need." },
      { q: "Can I generate more than one number?", a: "Yes. You can create a small list in one click." },
      { q: "Is this good for testing?", a: "Yes. It is useful for quick sample data." },
    ],
    related: ["uuid-generator", "percentage-calculator", "random-word-generator"],
  },
  {
    slug: "random-word-generator",
    h1: "Random Word Generator",
    title: "Random Word Generator Tool",
    description: "Generate a quick list of random words for ideas, names, or drafts.",
    keyword: "random word generator",
    intro: "Use this random word generator to get a quick word set when you need fresh input for writing or naming.",
    howTo: ["Choose a theme.", "Set how many words you want.", "Generate and copy the list."],
    useCases: ["Start a naming session.", "Feed a brainstorming prompt.", "Create simple placeholder content."],
    whyUseful: ["It gives you quick input when your own ideas feel stuck.", "The words are easy to scan and reuse.", "It keeps the task simple and fast."],
    faqs: [
      { q: "Can I use a theme?", a: "Yes. Pick a theme to steer the word set." },
      { q: "Is this useful for writing?", a: "Yes. It is handy for prompts and idea generation." },
      { q: "Can I copy the full list?", a: "Yes. The list is ready to copy in one action." },
    ],
    related: ["lorem-ipsum-generator", "anagram-generator", "title-generator"],
  },
  {
    slug: "lorem-ipsum-generator",
    h1: "Lorem Ipsum Generator",
    title: "Lorem Ipsum Generator Tool",
    description: "Create quick placeholder text for layouts, mockups, and drafts.",
    keyword: "lorem ipsum generator",
    intro: "Use this lorem ipsum generator when you need fast placeholder copy for a layout or mockup.",
    howTo: ["Choose how much text you need.", "Generate the placeholder block.", "Copy it into your layout or design."],
    useCases: ["Fill a wireframe quickly.", "Replace empty copy blocks.", "Test spacing in a page layout."],
    whyUseful: ["It saves time during design and layout work.", "The output is clean and ready to paste.", "It keeps the focus on structure instead of wording."],
    faqs: [
      { q: "Can I make it longer?", a: "Yes. Generate more paragraphs or sentences as needed." },
      { q: "Is this only for designers?", a: "No. It is also useful for developers and editors." },
      { q: "Can I copy the full block?", a: "Yes. The generated text is easy to copy." },
    ],
    related: ["text-case-converter", "title-generator", "word-cloud-generator"],
  },
  {
    slug: "color-palette-generator",
    h1: "Color Palette Generator",
    title: "Color Palette Generator Tool",
    description: "Generate a quick palette of matching colors for a page or brand.",
    keyword: "color palette generator",
    intro: "Use this color palette generator when you need a quick set of matching colors for a layout or visual system.",
    howTo: ["Choose a seed color or style.", "Generate a five-color palette.", "Copy the hex values you want to use."],
    useCases: ["Build a page color system.", "Test accent and background colors.", "Kick off a brand direction."],
    whyUseful: ["It gives you a quick starting point for visual decisions.", "The palette is easy to copy into CSS or design tools.", "It keeps the workflow focused on getting a usable result fast."],
    faqs: [
      { q: "Can I use the hex values directly?", a: "Yes. The colors are ready to paste into code or design files." },
      { q: "Is this random or themed?", a: "It can work as a quick random color generator with a consistent palette feel." },
      { q: "Does it include multiple colors?", a: "Yes. It generates a small set of matching swatches." },
    ],
    related: ["color-picker-tool", "font-generator-tool", "random-word-generator"],
  },
  {
    slug: "font-generator-tool",
    h1: "Font Generator Tool",
    title: "Font Generator Tool",
    description: "Preview simple font styles and copy a basic font-family snippet.",
    keyword: "fancy font generator",
    intro: "Use this font generator tool when you want to compare a few quick font styles for a title or page.",
    howTo: ["Type a sample line.", "Pick a font style.", "Copy the font-family snippet if it fits."],
    useCases: ["Test a headline look.", "Pick a quick display style.", "Share a starter font direction."],
    whyUseful: ["It makes typography checks fast.", "The preview is easy to read and compare.", "It helps you move from idea to layout quickly."],
    faqs: [
      { q: "Can I preview cursive styles?", a: "Yes. You can switch between a few basic styles." },
      { q: "Is this useful for landing pages?", a: "Yes. It is a quick way to sanity-check a headline style." },
      { q: "Can I copy the CSS?", a: "Yes. The font-family snippet is ready to copy." },
    ],
    related: ["text-case-converter", "color-palette-generator", "title-generator"],
  },
  {
    slug: "hashtag-generator",
    h1: "Hashtag Generator",
    title: "Hashtag Generator Tool",
    description: "Generate quick hashtags from a topic or phrase.",
    keyword: "hashtag generator",
    intro: "Use this hashtag generator to get a fast set of tags from a short topic or campaign phrase.",
    howTo: ["Enter a topic or phrase.", "Choose how many tags you want.", "Generate and copy the list."],
    useCases: ["Draft social captions.", "Prepare event tags.", "Build a quick content set."],
    whyUseful: ["It helps you move from a topic to usable tags in one step.", "The output is short and easy to copy.", "It avoids manual tag writing when you need a quick set."],
    faqs: [
      { q: "Can I use this for a wedding?", a: "Yes. It is also useful for event-style hashtag ideas." },
      { q: "Does it make multiple tags?", a: "Yes. It can generate a small set at once." },
      { q: "Can I edit the list?", a: "Yes. Copy what you like and trim the rest." },
    ],
    related: ["slogan-generator", "title-generator", "word-cloud-generator"],
  },
  {
    slug: "slogan-generator",
    h1: "Slogan Generator",
    title: "Slogan Generator Tool",
    description: "Generate short slogan ideas for a product, brand, or project.",
    keyword: "slogan generator",
    intro: "Use this slogan generator when you need a short line that explains what a brand does.",
    howTo: ["Enter a brand name.", "Add the category or use case.", "Generate a few slogan options."],
    useCases: ["Draft a hero line.", "Explore a brand direction.", "Create quick marketing copy."],
    whyUseful: ["It gives you short, clear phrasing fast.", "The lines are easy to compare side by side.", "It keeps the copywriting step moving."],
    faqs: [
      { q: "Can I use the slogans on a landing page?", a: "Yes. They are short enough for headers and subheads." },
      { q: "Can I change the brand name?", a: "Yes. The output updates from your input." },
      { q: "Does it make multiple options?", a: "Yes. You get a small batch of ideas." },
    ],
    related: ["business-name-generator", "title-generator", "acronym-generator"],
  },
  {
    slug: "business-name-generator",
    h1: "Business Name Generator",
    title: "Business Name Generator Tool",
    description: "Generate quick business and brand name ideas from a short topic.",
    keyword: "business name generator",
    intro: "Use this business name generator to get a quick set of brand-style names from a short topic or niche.",
    howTo: ["Enter the type of business.", "Generate a short list of names.", "Copy the ones you want to keep."],
    useCases: ["Start a brand naming session.", "Brainstorm a side project name.", "Get a simple name list for review."],
    whyUseful: ["It is a fast way to move from an idea to options.", "The names are short enough to scan quickly.", "It helps you get unstuck without a big process."],
    faqs: [
      { q: "Is this useful for restaurants?", a: "Yes. It can create short name ideas for many categories." },
      { q: "Can I use it for team names?", a: "Yes. It works well for team or project naming too." },
      { q: "Are the names ready to copy?", a: "Yes. You can copy the ones that fit best." },
    ],
    related: ["slogan-generator", "username-generator", "title-generator"],
  },
  {
    slug: "email-generator",
    h1: "Email Generator",
    title: "Email Generator Tool",
    description: "Generate temporary-style email addresses for tests and demos.",
    keyword: "email generator",
    intro: "Use this email generator when you need sample addresses for testing, signup flows, or demos.",
    howTo: ["Enter a name and domain.", "Choose how many addresses you need.", "Generate and copy the list."],
    useCases: ["Fill a form during development.", "Create sample contacts.", "Prepare a simple test set."],
    whyUseful: ["It saves time when you need a few fake addresses.", "The result is easy to copy and paste.", "It keeps test data creation simple."],
    faqs: [
      { q: "Can I use my own domain?", a: "Yes. Enter the domain you want to use." },
      { q: "Does it create multiple emails?", a: "Yes. You can generate a small set quickly." },
      { q: "Is this only for developers?", a: "Mostly, but it is useful anywhere sample emails are needed." },
    ],
    related: ["uuid-generator", "random-number-generator", "phone-number-generator"],
  },
  {
    slug: "uuid-generator",
    h1: "UUID Generator",
    title: "UUID Generator Tool",
    description: "Generate quick UUID values for records, keys, and test data.",
    keyword: "uuid generator",
    intro: "Use this UUID generator when you need unique identifiers for a record, test, or quick sample.",
    howTo: ["Choose how many IDs you need.", "Generate the UUIDs.", "Copy or download the result."],
    useCases: ["Create sample IDs.", "Fill test forms.", "Add unique values to mock data."],
    whyUseful: ["It gives you a unique value in one click.", "The output is ready for development and testing.", "It avoids manual ID creation."],
    faqs: [
      { q: "Is this random?", a: "Yes. The IDs are generated with browser crypto APIs." },
      { q: "Can I create several at once?", a: "Yes. Choose how many UUIDs you want." },
      { q: "Can I copy them all?", a: "Yes. The list is ready to copy as plain text." },
    ],
    related: ["email-generator", "random-number-generator", "barcode-generator"],
  },
  {
    slug: "barcode-generator",
    h1: "Barcode Generator",
    title: "Barcode Generator Tool",
    description: "Create a simple barcode preview for a code or product value.",
    keyword: "barcode generator",
    intro: "Use this barcode generator to create a quick barcode-style preview for a code, label, or product value.",
    howTo: ["Enter the value.", "Generate the barcode preview.", "Download the SVG when it looks right."],
    useCases: ["Mock a product label.", "Test a code in a layout.", "Create a simple printable asset."],
    whyUseful: ["It is a quick visual stand-in for a barcode.", "The SVG is easy to reuse in layouts.", "It helps you get a product mockup moving."],
    faqs: [
      { q: "Can I download it?", a: "Yes. The SVG download is ready once generated." },
      { q: "Is this good for mockups?", a: "Yes. It is a simple preview for layout work." },
      { q: "Can I change the value?", a: "Yes. The preview updates from your input." },
    ],
    related: ["uuid-generator", "word-cloud-generator", "color-palette-generator"],
  },
  {
    slug: "word-cloud-generator",
    h1: "Word Cloud Generator",
    title: "Word Cloud Generator Tool",
    description: "Turn a list of words into a simple word cloud preview.",
    keyword: "word cloud generator",
    intro: "Use this word cloud generator when you want a quick visual summary of a set of words or phrases.",
    howTo: ["Paste words or phrases.", "Generate the cloud.", "Copy the words or reuse the preview."],
    useCases: ["Summarize notes.", "Visualize a topic set.", "Create a simple content graphic."],
    whyUseful: ["It turns a list into something easier to scan.", "The preview is quick and lightweight.", "It helps you get a visual result without a heavy tool."],
    faqs: [
      { q: "Can I paste comma-separated words?", a: "Yes. Any comma or line-separated list works." },
      { q: "Is this useful for reports?", a: "Yes. It is a quick visual summary for a topic list." },
      { q: "Can I copy the words?", a: "Yes. The input list is ready to reuse." },
    ],
    related: ["lorem-ipsum-generator", "title-generator", "plot-generator"],
  },
  {
    slug: "title-generator",
    h1: "Title Generator",
    title: "Title Generator Tool",
    description: "Generate quick title ideas for a page, post, or section.",
    keyword: "title generator",
    intro: "Use this title generator when you want a quick set of headline ideas for a page or article.",
    howTo: ["Enter the topic.", "Generate a few title ideas.", "Copy the one you want to use."],
    useCases: ["Draft a blog title.", "Name a page section.", "Explore a quick headline direction."],
    whyUseful: ["It gets you from a topic to usable lines fast.", "The output is easy to compare.", "It keeps the writing step simple."],
    faqs: [
      { q: "Can I use this for blog posts?", a: "Yes. It is useful for quick post title ideas." },
      { q: "Does it make several options?", a: "Yes. You get a small set of title ideas." },
      { q: "Can I change the topic?", a: "Yes. Enter any page or post topic." },
    ],
    related: ["slogan-generator", "plot-generator", "acronym-generator"],
  },
  {
    slug: "acronym-generator",
    h1: "Acronym Generator",
    title: "Acronym Generator Tool",
    description: "Build short acronym ideas from a phrase or project name.",
    keyword: "acronym generator",
    intro: "Use this acronym generator when you need a short abbreviation from a name or phrase.",
    howTo: ["Enter the phrase.", "Generate a few acronym options.", "Copy the one that fits best."],
    useCases: ["Shorten a project name.", "Explore branding ideas.", "Create a compact internal label."],
    whyUseful: ["It makes a short form from longer text quickly.", "The output is easy to scan and copy.", "It is useful for naming and planning work."],
    faqs: [
      { q: "Can I use several words?", a: "Yes. The generator works from a phrase." },
      { q: "Does it make more than one acronym?", a: "Yes. It gives you a small set of options." },
      { q: "Can I use it for brand names?", a: "Yes. It is a helpful naming shortcut." },
    ],
    related: ["business-name-generator", "title-generator", "ascii-art-generator"],
  },
  {
    slug: "ascii-art-generator",
    h1: "ASCII Art Generator",
    title: "ASCII Art Generator Tool",
    description: "Create a simple ASCII-style banner for text or a short label.",
    keyword: "ascii art generator",
    intro: "Use this ASCII art generator when you want a quick text banner or a small block-style preview.",
    howTo: ["Type the text.", "Generate the banner.", "Copy it into notes or docs."],
    useCases: ["Make a fun heading.", "Add style to a draft.", "Create a quick plain-text banner."],
    whyUseful: ["It gives you a visual text block fast.", "The output works well in plain text contexts.", "It is a quick way to add a little personality."],
    faqs: [
      { q: "Can I copy the banner?", a: "Yes. The output is plain text and easy to copy." },
      { q: "Is this good for fun text?", a: "Yes. It is meant for simple, playful banners." },
      { q: "Can I change the text?", a: "Yes. Enter any short label or phrase." },
    ],
    related: ["acronym-generator", "plot-generator", "title-generator"],
  },
  {
    slug: "plot-generator",
    h1: "Plot Generator",
    title: "Plot Generator Tool",
    description: "Generate a structured plot package with logline, beats, stakes, and title ideas.",
    keyword: "plot generator",
    intro: "Use this plot generator when you need a structured story seed with a usable arc instead of a shallow one-line prompt.",
    howTo: ["Enter a topic, character, or concept.", "Generate the plot package.", "Copy the logline, beats, or title ideas you want to keep."],
    useCases: ["Start a story draft with more direction.", "Explore a narrative prompt with stakes.", "Create a cleaner writing seed for fiction or content."],
    whyUseful: ["It gives you a fuller story direction fast.", "The beats and stakes are easier to adapt than a single sentence.", "It keeps the writing process moving without feeling generic."],
    faqs: [
      { q: "Is this only for fiction?", a: "No. It works for prompts, story ideas, and content outlines in general." },
      { q: "Can I change the topic?", a: "Yes. Enter any subject you want." },
      { q: "Does it make multiple beats?", a: "Yes. It gives you a short sequence of beats, plus supporting title ideas." },
    ],
    related: ["lorem-ipsum-generator", "title-generator", "word-cloud-generator"],
  },
  {
    slug: "anagram-generator",
    h1: "Anagram Generator",
    title: "Anagram Generator Tool",
    description: "Shuffle a word into a quick set of anagram-style results.",
    keyword: "anagram generator",
    intro: "Use this anagram generator when you need a quick word shuffle for ideas or playful variations.",
    howTo: ["Enter a word.", "Generate the shuffles.", "Copy the result you like."],
    useCases: ["Brainstorm a playful name.", "Explore a word puzzle.", "Create a quick variation list."],
    whyUseful: ["It gives you a few rearranged options quickly.", "The results are easy to scan.", "It is a simple way to explore word variations."],
    faqs: [
      { q: "Do I need a long word?", a: "No. Short words work too, though longer words give more variety." },
      { q: "Can I copy the list?", a: "Yes. The output is ready to copy." },
      { q: "Is this useful for names?", a: "Yes. It can spark a quick naming direction." },
    ],
    related: ["random-word-generator", "business-name-generator", "acronym-generator"],
  },
  {
    slug: "phone-number-generator",
    h1: "Phone Number Generator",
    title: "Phone Number Generator Tool",
    description: "Generate sample phone numbers for forms, tests, and mock data.",
    keyword: "phone number generator",
    intro: "Use this phone number generator when you need a quick set of sample numbers for a form or test.",
    howTo: ["Choose how many numbers you need.", "Generate the sample list.", "Copy the numbers into your test data."],
    useCases: ["Fill a sign-up form.", "Create mock contact data.", "Test validation fields."],
    whyUseful: ["It saves time when you need placeholder contacts.", "The output is simple to copy.", "It keeps test data creation quick."],
    faqs: [
      { q: "Can I generate more than one?", a: "Yes. You can make a small list at once." },
      { q: "Is this for testing only?", a: "Mostly, yes. It is best used for sample data." },
      { q: "Can I copy the numbers?", a: "Yes. The list is ready to copy." },
    ],
    related: ["email-generator", "uuid-generator", "random-number-generator"],
  },
  {
    slug: "random-letter-generator",
    h1: "Random Letter Generator",
    title: "Random Letter Generator Tool",
    description: "Generate quick random letter sets for puzzles, placeholders, and tiny naming ideas.",
    keyword: "random letter generator",
    intro: "Use this random letter generator when you need a fast set of letters for a game, puzzle, or placeholder task.",
    howTo: ["Choose how many letters you want.", "Generate the list.", "Copy the letters you need."],
    useCases: ["Build puzzle prompts.", "Create placeholder symbols.", "Test layouts with simple text."],
    whyUseful: ["It is fast when you only need single characters.", "The result is easy to scan.", "It keeps small text tasks simple."],
    faqs: [{ q: "Can I make a longer list?", a: "Yes. You can generate a bigger set when you need more samples." }, { q: "Is this good for games?", a: "Yes. It works well for puzzles and quick character prompts." }, { q: "Can I copy the output?", a: "Yes. The result is ready to copy." }],
    related: ["random-word-generator", "anagram-generator", "acronym-generator"],
  },
  {
    slug: "random-animal-generator",
    h1: "Random Animal Generator",
    title: "Random Animal Generator Tool",
    description: "Generate random animal names for lists, prompts, and simple creative ideas.",
    keyword: "random animal generator",
    intro: "Use this random animal generator when you need a quick animal list for a prompt, game, or test.",
    howTo: ["Choose the number of animals.", "Generate the set.", "Copy the result when it looks right."],
    useCases: ["Write prompt ideas.", "Fill example lists.", "Create quick themed labels."],
    whyUseful: ["Animal lists are easy to read and reuse.", "It is a quick way to get simple creative prompts.", "The output is short and direct."],
    faqs: [{ q: "Are these real animals?", a: "They are common animal names that work for quick lists." }, { q: "Can I copy the list?", a: "Yes. It is ready to copy." }, { q: "Does it make long lists?", a: "Yes. You can generate a bigger set when needed." }],
    related: ["random-word-generator", "story-prompt-generator", "character-name-generator"],
  },
  {
    slug: "random-city-generator",
    h1: "Random City Generator",
    title: "Random City Generator Tool",
    description: "Generate quick city-style names for mockups, maps, and creative projects.",
    keyword: "random city generator",
    intro: "Use this random city generator when you need a fast list of city names for demos, writing, or layouts.",
    howTo: ["Pick how many cities you need.", "Generate the list.", "Copy the cities into your project."],
    useCases: ["Label map examples.", "Name sample locations.", "Write worldbuilding notes."],
    whyUseful: ["City names make placeholders feel more complete.", "The result is fast to reuse in mockups.", "It keeps location naming simple."],
    faqs: [{ q: "Are these real cities?", a: "The tool creates city-style names for examples and mockups." }, { q: "Can I use them in a story?", a: "Yes. They are useful as placeholder location names." }, { q: "Can I make more than one list?", a: "Yes. Generate again whenever you need a different set." }],
    related: ["random-country-generator", "story-prompt-generator", "random-word-generator"],
  },
  {
    slug: "random-country-generator",
    h1: "Random Country Generator",
    title: "Random Country Generator Tool",
    description: "Generate random country names for quizzes, forms, and simple reference lists.",
    keyword: "random country generator",
    intro: "Use this random country generator when you need a quick country list for a form, quiz, or sample data.",
    howTo: ["Choose how many countries you need.", "Generate the result.", "Copy the list when it is ready."],
    useCases: ["Build trivia prompts.", "Fill sample forms.", "Create location examples."],
    whyUseful: ["It is a quick source of familiar place names.", "The output is easy to paste into other tools.", "It keeps reference tasks lightweight."],
    faqs: [{ q: "Is this a geography quiz tool?", a: "It can be used that way, but it is also helpful for sample lists." }, { q: "Can I reuse the output?", a: "Yes. Copy it into your notes or mockups." }, { q: "Does it change each time?", a: "Yes. Each generation gives a new set." }],
    related: ["random-city-generator", "headline-generator", "secret-santa-generator"],
  },
  {
    slug: "fantasy-name-generator",
    h1: "Fantasy Name Generator",
    title: "Fantasy Name Generator Tool",
    description: "Generate fantasy names for games, stories, characters, and worldbuilding notes.",
    keyword: "fantasy name generator",
    intro: "Use this fantasy name generator when you need a quick name set for a game, story, or character sheet.",
    howTo: ["Choose the tone you want.", "Generate the names.", "Copy the one that fits your idea."],
    useCases: ["Name characters.", "Build world lore.", "Draft game assets."],
    whyUseful: ["It gives you quick naming options.", "The names feel useful for creative work.", "It reduces blank-page friction."],
    faqs: [{ q: "Can I make darker names?", a: "Yes. You can steer the tone toward darker or heroic styles." }, { q: "Are these original?", a: "They are generated combinations built for inspiration." }, { q: "Can I use them in a game?", a: "Yes. They are meant for quick creative use." }],
    related: ["character-name-generator", "story-prompt-generator", "plot-twist-generator"],
  },
  {
    slug: "superhero-name-generator",
    h1: "Superhero Name Generator",
    title: "Superhero Name Generator Tool",
    description: "Generate superhero-style names for stories, games, and fan projects.",
    keyword: "superhero name generator",
    intro: "Use this superhero name generator when you need a bold character name for a story, team, or project.",
    howTo: ["Pick a naming direction.", "Generate a few options.", "Copy the one that matches the character."],
    useCases: ["Create comic names.", "Name fictional teams.", "Build prompt starters."],
    whyUseful: ["It gives you fast hero-style names.", "The output is easy to skim.", "It helps with quick creative drafting."],
    faqs: [{ q: "Can I use this for team names?", a: "Yes. It also works well for fictional groups." }, { q: "Are the names serious or playful?", a: "They are balanced to work for both styles." }, { q: "Can I generate more?", a: "Yes. Refresh to get a different set." }],
    related: ["team-name-generator", "character-name-generator", "fantasy-name-generator"],
  },
  {
    slug: "fake-data-generator",
    h1: "Fake Data Generator",
    title: "Fake Data Generator Tool",
    description: "Generate quick mock rows for testing forms, layouts, and sample dashboards.",
    keyword: "fake data generator",
    intro: "Use this fake data generator when you need simple placeholder rows for testing or layout work.",
    howTo: ["Choose the number of rows.", "Generate the sample data.", "Copy it into your test flow."],
    useCases: ["Test tables.", "Fill mock profiles.", "Preview export layouts."],
    whyUseful: ["It gives you fast placeholder content.", "The output is easy to paste into tests.", "It saves time when you need sample rows."],
    faqs: [{ q: "Is this for production data?", a: "No. It is intended for mock and test data." }, { q: "Can I use it in tables?", a: "Yes. It is useful for table and form previews." }, { q: "Does it create different rows each time?", a: "Yes. Each run changes the data." }],
    related: ["json-formatter", "email-generator", "uuid-generator"],
  },
  {
    slug: "secret-santa-generator",
    h1: "Secret Santa Generator",
    title: "Secret Santa Generator Tool",
    description: "Generate simple Secret Santa pairings from a list of names.",
    keyword: "secret santa generator",
    intro: "Use this secret santa generator when you need a quick pairing list from a group of names.",
    howTo: ["Paste the names, one per line.", "Generate the pairings.", "Copy the assignment list."],
    useCases: ["Set up office exchanges.", "Organize friend groups.", "Build holiday pairing lists."],
    whyUseful: ["It keeps the pairing step simple.", "The output is easy to share.", "It works well for small groups."],
    faqs: [{ q: "How many names do I need?", a: "At least two names are required." }, { q: "Can I copy the pairings?", a: "Yes. The result is ready to copy." }, { q: "Does it avoid self-pairing?", a: "Yes. It tries to keep each person paired with someone else." }],
    related: ["bingo-card-generator", "team-name-generator", "random-city-generator"],
  },
  {
    slug: "bingo-card-generator",
    h1: "Bingo Card Generator",
    title: "Bingo Card Generator Tool",
    description: "Generate a simple bingo card from a list of words or phrases.",
    keyword: "bingo card generator",
    intro: "Use this bingo card generator when you need a quick card layout for events, meetings, or games.",
    howTo: ["Paste or choose your words.", "Generate the bingo card.", "Copy the board or reuse the words."],
    useCases: ["Make meeting bingo.", "Create classroom games.", "Build event activities."],
    whyUseful: ["It creates a ready-to-use board quickly.", "The center free space is included.", "It keeps event setup lightweight."],
    faqs: [{ q: "Does it use a free space?", a: "Yes. The center cell is marked as FREE." }, { q: "Can I change the words?", a: "Yes. Paste your own list before generating." }, { q: "Is it good for games?", a: "Yes. It works well for simple bingo-style activities." }],
    related: ["secret-santa-generator", "story-prompt-generator", "headline-generator"],
  },
  {
    slug: "truth-table-generator",
    h1: "Truth Table Generator",
    title: "Truth Table Generator Tool",
    description: "Generate a quick boolean truth table for common logic operations.",
    keyword: "truth table generator",
    intro: "Use this truth table generator when you need a quick logic table for boolean checks or study notes.",
    howTo: ["Choose the logic mode.", "Generate the table.", "Copy the rows you need."],
    useCases: ["Study logic basics.", "Check boolean rules.", "Build simple teaching notes."],
    whyUseful: ["The table is short and readable.", "It is useful for quick logic checks.", "It removes manual truth-table work."],
    faqs: [{ q: "What operations are included?", a: "AND, OR, XOR, NAND, NOR, and IMPLIES are available." }, { q: "Can I copy the rows?", a: "Yes. The table is easy to copy from the page." }, { q: "Is this useful for studying?", a: "Yes. It is a fast way to see boolean results." }],
    related: ["json-formatter", "percentage-calculator", "sequence-generator"],
  },
  {
    slug: "rhyming-word-generator",
    h1: "Rhyming Word Generator",
    title: "Rhyming Word Generator Tool",
    description: "Generate words that rhyme with a target word for writing and games.",
    keyword: "rhyming word generator",
    intro: "Use this rhyming word generator when you need a quick rhyme list for writing, songs, or wordplay.",
    howTo: ["Type the word you want to rhyme.", "Generate the result.", "Copy the best options."],
    useCases: ["Write lyrics.", "Build tongue-twister ideas.", "Create poetry prompts."],
    whyUseful: ["It helps when you need fast wordplay options.", "The list is short and direct.", "It works well for creative drafting."],
    faqs: [{ q: "Do the words always rhyme perfectly?", a: "They are rhyme-style suggestions and may vary in strictness." }, { q: "Can I use a short word?", a: "Yes. Short words still work." }, { q: "Can I copy the list?", a: "Yes. The result is ready to copy." }],
    related: ["anagram-generator", "story-prompt-generator", "fancy-text-generator"],
  },
  {
    slug: "color-scheme-generator",
    h1: "Color Scheme Generator",
    title: "Color Scheme Generator Tool",
    description: "Generate compact color scheme ideas with quick hex palettes.",
    keyword: "color scheme generator",
    intro: "Use this color scheme generator when you need a fast palette set for a mockup, brand page, or layout.",
    howTo: ["Enter a seed word.", "Generate the schemes.", "Copy the palette you like."],
    useCases: ["Pick brand colors.", "Explore page palettes.", "Test visual direction."],
    whyUseful: ["It gives a few palette directions fast.", "The colors are easy to compare.", "It keeps early design work moving."],
    faqs: [{ q: "Are the colors stable?", a: "They are generated from the seed and vary by input." }, { q: "Can I copy the hex values?", a: "Yes. The output includes the codes." }, { q: "Is this good for mockups?", a: "Yes. It is useful for early visual exploration." }],
    related: ["color-palette-generator", "color-picker-tool", "font-generator-tool"],
  },
  {
    slug: "headline-generator",
    h1: "Headline Generator",
    title: "Headline Generator Tool",
    description: "Generate quick headline ideas for pages, posts, and product copy.",
    keyword: "headline generator",
    intro: "Use this headline generator when you need a quick set of page or post headline ideas.",
    howTo: ["Add a topic.", "Generate headline ideas.", "Copy the one that fits best."],
    useCases: ["Draft landing page copy.", "Write section headings.", "Explore article hooks."],
    whyUseful: ["It gives you fast writing options.", "The ideas are short and direct.", "It helps you move from blank to draft."],
    faqs: [{ q: "Is this for articles or landing pages?", a: "It can help with both." }, { q: "Can I make more than one set?", a: "Yes. Generate again with a new topic." }, { q: "Can I copy the headlines?", a: "Yes. They are ready to paste." }],
    related: ["title-generator", "slogan-generator", "ai-prompt-starter-generator"],
  },
  {
    slug: "thesis-statement-generator",
    h1: "Thesis Statement Generator",
    title: "Thesis Statement Generator Tool",
    description: "Generate a concise thesis statement for essays and research drafts.",
    keyword: "thesis statement generator",
    intro: "Use this thesis statement generator when you need a concise main claim for an essay or draft.",
    howTo: ["Enter your topic.", "Generate a thesis.", "Copy the statement into your draft."],
    useCases: ["Start essays.", "Build paper outlines.", "Frame a research argument."],
    whyUseful: ["It helps you get past the first sentence.", "The statement is compact and easy to edit.", "It keeps drafting focused."],
    faqs: [{ q: "Is this a full essay?", a: "No. It generates a single thesis-style sentence." }, { q: "Can I edit the result?", a: "Yes. It is meant as a starting point." }, { q: "Is it useful for students?", a: "Yes. It helps with outline work and first drafts." }],
    related: ["headline-generator", "ai-prompt-starter-generator", "plot-generator"],
  },
  {
    slug: "restaurant-name-generator",
    h1: "Restaurant Name Generator",
    title: "Restaurant Name Generator Tool",
    description: "Generate restaurant-style names for menus, mockups, and creative concepts.",
    keyword: "restaurant name generator",
    intro: "Use this restaurant name generator when you need a quick food business name for a mockup or idea.",
    howTo: ["Enter the cuisine or style.", "Generate names.", "Copy a name that fits."],
    useCases: ["Mock up a brand.", "Name a concept menu.", "Brainstorm food ideas."],
    whyUseful: ["It gives you quick naming options.", "The names feel usable in mockups.", "It reduces naming friction."],
    faqs: [{ q: "Can I use the cuisine as a seed?", a: "Yes. That helps steer the results." }, { q: "Are these polished names?", a: "They are simple and practical naming ideas." }, { q: "Can I generate more names?", a: "Yes. Refresh to get another set." }],
    related: ["business-name-generator", "product-name-generator", "startup-idea-generator"],
  },
  {
    slug: "fancy-text-generator",
    h1: "Fancy Text Generator",
    title: "Fancy Text Generator Tool",
    description: "Turn plain text into a stylized text version for headings and posts.",
    keyword: "fancy text generator",
    intro: "Use this fancy text generator when you want a stylized version of a short phrase.",
    howTo: ["Enter the phrase.", "Generate the styled text.", "Copy the result you like."],
    useCases: ["Decorate a heading.", "Style a social post.", "Make text look different."],
    whyUseful: ["It gives you a fast visual variation.", "The output is easy to copy.", "It works well for short phrases."],
    faqs: [{ q: "Is this just a font?", a: "It produces stylized Unicode text, not a font file." }, { q: "Can I use it in captions?", a: "Yes. It is useful for short copy." }, { q: "Does it support long text?", a: "Short phrases work best." }],
    related: ["glitch-text-generator", "title-generator", "slogan-generator"],
  },
  {
    slug: "glitch-text-generator",
    h1: "Glitch Text Generator",
    title: "Glitch Text Generator Tool",
    description: "Create a glitched text effect for short phrases and creative posts.",
    keyword: "glitch text generator",
    intro: "Use this glitch text generator when you want a noisy text effect for a label, caption, or header.",
    howTo: ["Enter a short phrase.", "Generate the effect.", "Copy the glitchy result."],
    useCases: ["Style a title.", "Create a cyber look.", "Make a post stand out."],
    whyUseful: ["It is quick to generate.", "The result has a clear visual edge.", "It works best on short phrases."],
    faqs: [{ q: "Can I use long phrases?", a: "Short text works best for readability." }, { q: "Is it a visual effect?", a: "Yes. It uses a text-based glitch style." }, { q: "Can I copy the result?", a: "Yes. Copy the text directly from the page." }],
    related: ["fancy-text-generator", "ascii-art-generator", "title-generator"],
  },
  {
    slug: "mla-citation-generator",
    h1: "MLA Citation Generator",
    title: "MLA Citation Generator Tool",
    description: "Generate a basic MLA-style citation line for pages and simple sources.",
    keyword: "mla citation generator",
    intro: "Use this MLA citation generator when you need a quick citation line for a page or source note.",
    howTo: ["Add the source details.", "Generate the citation.", "Copy it into your notes."],
    useCases: ["Draft a bibliography.", "Record source info.", "Prepare study notes."],
    whyUseful: ["It helps you move quickly from source to draft.", "The citation is compact.", "It is easier than formatting manually."],
    faqs: [{ q: "Is it a full bibliography tool?", a: "No. It generates a basic MLA-style citation line." }, { q: "Can I edit the output?", a: "Yes. It is meant as a draft starting point." }, { q: "Is it useful for quick notes?", a: "Yes. It is handy for fast reference capture." }],
    related: ["json-formatter", "thesis-statement-generator", "headline-generator"],
  },
  {
    slug: "business-niche-generator",
    h1: "Business Niche Generator",
    title: "Business Niche Generator Tool",
    description: "Generate quick business niche ideas for products, services, and micro-apps.",
    keyword: "business niche generator",
    intro: "Use this business niche generator when you want a fast set of niche ideas for a product or service.",
    howTo: ["Enter a seed word.", "Generate niches.", "Pick the best fit."],
    useCases: ["Find product angles.", "Brainstorm side projects.", "Shape service ideas."],
    whyUseful: ["It helps with early idea work.", "The output is short and direct.", "It gives you multiple directions fast."],
    faqs: [{ q: "Is this for market research?", a: "It is an idea generator, not a full research tool." }, { q: "Can I use the ideas for apps?", a: "Yes. They are useful as starting points." }, { q: "Can I generate more?", a: "Yes. Change the seed and try again." }],
    related: ["startup-idea-generator", "product-name-generator", "tagline-generator"],
  },
  {
    slug: "product-name-generator",
    h1: "Product Name Generator",
    title: "Product Name Generator Tool",
    description: "Generate product name ideas for apps, features, and small tools.",
    keyword: "product name generator",
    intro: "Use this product name generator when you need a quick naming set for an app or feature.",
    howTo: ["Add a seed word.", "Generate names.", "Copy the one that feels right."],
    useCases: ["Name a feature.", "Brainstorm a launch title.", "Create concept labels."],
    whyUseful: ["It gives you direct naming ideas.", "The names are simple and practical.", "It is good for short brainstorming sessions."],
    faqs: [{ q: "Can I use the seed to guide the output?", a: "Yes. That helps shape the results." }, { q: "Is it good for features?", a: "Yes. It works well for product and feature naming." }, { q: "Can I regenerate?", a: "Yes. Change the seed or refresh the page." }],
    related: ["business-name-generator", "startup-idea-generator", "tagline-generator"],
  },
  {
    slug: "startup-idea-generator",
    h1: "Startup Idea Generator",
    title: "Startup Idea Generator Tool",
    description: "Generate quick startup ideas for apps, tools, and side projects.",
    keyword: "startup idea generator",
    intro: "Use this startup idea generator when you need a simple list of product directions to explore.",
    howTo: ["Add a seed or topic.", "Generate startup ideas.", "Choose one to refine."],
    useCases: ["Brainstorm side projects.", "Explore app directions.", "Kick off product planning."],
    whyUseful: ["It gives you fast directions to consider.", "The ideas are easy to expand.", "It helps with early ideation."],
    faqs: [{ q: "Are these full business plans?", a: "No. They are idea starters." }, { q: "Can I turn one into a real product?", a: "Yes. They are meant for quick concept work." }, { q: "Can I generate more ideas?", a: "Yes. Try a new seed when you want a different angle." }],
    related: ["business-niche-generator", "product-name-generator", "ai-prompt-starter-generator"],
  },
  {
    slug: "story-prompt-generator",
    h1: "Story Prompt Generator",
    title: "Story Prompt Generator Tool",
    description: "Generate simple story prompts for writing, roleplay, and creative warmups.",
    keyword: "story prompt generator",
    intro: "Use this story prompt generator when you want a fast prompt to start a scene or story.",
    howTo: ["Enter a seed idea.", "Generate prompts.", "Pick one to expand."],
    useCases: ["Start a scene.", "Warm up writing.", "Build character ideas."],
    whyUseful: ["It helps overcome blank-page friction.", "The prompts are easy to extend.", "It is useful for short creative sessions."],
    faqs: [{ q: "Are the prompts long?", a: "They are short and easy to build on." }, { q: "Can I use them for roleplay?", a: "Yes. They are flexible enough for that." }, { q: "Can I generate more?", a: "Yes. Use a new seed for more options." }],
    related: ["plot-generator", "plot-twist-generator", "character-name-generator"],
  },
  {
    slug: "plot-twist-generator",
    h1: "Plot Twist Generator",
    title: "Plot Twist Generator Tool",
    description: "Generate quick plot twist ideas for stories and creative outlines.",
    keyword: "plot twist generator",
    intro: "Use this plot twist generator when you need a quick story turn or surprise idea.",
    howTo: ["Choose a seed idea.", "Generate twists.", "Copy the one you want to explore."],
    useCases: ["Write suspense scenes.", "Add tension to a draft.", "Explore surprise endings."],
    whyUseful: ["It gives you story tension quickly.", "The results are easy to rework.", "It is useful for draft exploration."],
    faqs: [{ q: "Are these major twists?", a: "They are simple twist starters that you can expand." }, { q: "Can I use them for outlines?", a: "Yes. They work well for story planning." }, { q: "Can I generate more?", a: "Yes. Refresh or change the seed." }],
    related: ["story-prompt-generator", "plot-generator", "character-name-generator"],
  },
  {
    slug: "word-mixer-generator",
    h1: "Word Mixer Generator",
    title: "Word Mixer Generator Tool",
    description: "Mix two words into quick mashups for names, labels, and concepts.",
    keyword: "word mixer generator",
    intro: "Use this word mixer generator when you want quick mashups from a pair of words.",
    howTo: ["Enter two words.", "Generate the mixes.", "Copy a combination you like."],
    useCases: ["Make a concept name.", "Try label ideas.", "Explore playful word blends."],
    whyUseful: ["It is fast for quick naming work.", "The output is easy to scan.", "It helps when you want shorter mashups."],
    faqs: [{ q: "Do I need two words?", a: "Yes. Two words give the best output." }, { q: "Can I use it for brands?", a: "Yes. It is handy for early name ideas." }, { q: "Can I copy the result?", a: "Yes. The mixes are ready to copy." }],
    related: ["product-name-generator", "business-name-generator", "tagline-generator"],
  },
  {
    slug: "sequence-generator",
    h1: "Sequence Generator",
    title: "Sequence Generator Tool",
    description: "Generate simple number sequences with a start, step, and count.",
    keyword: "sequence generator",
    intro: "Use this sequence generator when you need a quick numeric run for testing or examples.",
    howTo: ["Set the start value.", "Choose the step.", "Generate the sequence."],
    useCases: ["Test data entry.", "Build ordered examples.", "Create numeric patterns."],
    whyUseful: ["It makes patterned values quickly.", "The output is easy to copy.", "It is useful for sample data."],
    faqs: [{ q: "Can it count by twos or threes?", a: "Yes. Change the step value." }, { q: "Can I make longer runs?", a: "Yes. Increase the count." }, { q: "Is this useful for testing?", a: "Yes. It is a simple source of ordered numbers." }],
    related: ["random-number-generator", "truth-table-generator", "uuid-generator"],
  },
  {
    slug: "icon-label-generator",
    h1: "Icon Label Generator",
    title: "Icon Label Generator Tool",
    description: "Generate short label ideas for icons, badges, and compact UI pieces.",
    keyword: "icon label generator",
    intro: "Use this icon label generator when you need short label ideas for a badge, icon, or menu item.",
    howTo: ["Enter a seed word.", "Generate labels.", "Pick the shortest fit."],
    useCases: ["Name buttons.", "Label nav items.", "Create badge text."],
    whyUseful: ["It keeps labels short.", "The ideas fit compact UI elements.", "It helps with microcopy."],
    faqs: [{ q: "Are the labels very short?", a: "Yes. They are designed for compact UI use." }, { q: "Can I use them in a menu?", a: "Yes. They are useful for small interface labels." }, { q: "Can I generate another set?", a: "Yes. Enter a new seed or regenerate." }],
    related: ["title-generator", "tagline-generator", "headline-generator"],
  },
  {
    slug: "character-name-generator",
    h1: "Character Name Generator",
    title: "Character Name Generator Tool",
    description: "Generate character-style names for stories, games, and creative projects.",
    keyword: "character name generator",
    intro: "Use this character name generator when you need quick names for fictional characters.",
    howTo: ["Choose a tone.", "Generate names.", "Copy the one that fits the role."],
    useCases: ["Write fiction.", "Name game avatars.", "Build cast lists."],
    whyUseful: ["It gives you quick identity ideas.", "The names work in creative drafts.", "It is simple to use."],
    faqs: [{ q: "Can I choose the tone?", a: "Yes. The seed helps guide the style." }, { q: "Is this useful for games?", a: "Yes. It works well for character naming." }, { q: "Can I copy the names?", a: "Yes. The list is ready to copy." }],
    related: ["fantasy-name-generator", "superhero-name-generator", "story-prompt-generator"],
  },
  {
    slug: "team-name-generator",
    h1: "Team Name Generator",
    title: "Team Name Generator Tool",
    description: "Generate team name ideas for projects, sports, and groups.",
    keyword: "team name generator",
    intro: "Use this team name generator when you need a quick name set for a group or squad.",
    howTo: ["Add a seed word.", "Generate team names.", "Copy one for your group."],
    useCases: ["Name a project team.", "Create a sports team label.", "Build a club name."],
    whyUseful: ["It gives quick group naming options.", "The names are easy to scan.", "It helps groups pick a direction."],
    faqs: [{ q: "Can it be used for sports teams?", a: "Yes. It works for casual team naming." }, { q: "Does it generate lots of options?", a: "Yes. You can get several quick ideas." }, { q: "Can I copy them?", a: "Yes. The names are ready to copy." }],
    related: ["business-name-generator", "superhero-name-generator", "secret-santa-generator"],
  },
  {
    slug: "ai-prompt-starter-generator",
    h1: "AI Prompt Starter Generator",
    title: "AI Prompt Starter Generator Tool",
    description: "Generate prompt starters for planning, writing, and simple AI tasks.",
    keyword: "ai prompt starter generator",
    intro: "Use this AI prompt starter generator when you want a fast starting point for a task or idea.",
    howTo: ["Add a seed task.", "Generate prompt starters.", "Pick the one you want to expand."],
    useCases: ["Start a draft.", "Plan a workflow.", "Build a simple AI request."],
    whyUseful: ["It helps you get moving quickly.", "The prompts are short and direct.", "It works well for first drafts."],
    faqs: [{ q: "Are these full prompts?", a: "They are starters meant to be edited." }, { q: "Can I use them for planning?", a: "Yes. They are useful for early task planning." }, { q: "Can I make more?", a: "Yes. Change the seed and generate again." }],
    related: ["story-prompt-generator", "startup-idea-generator", "headline-generator"],
  },
  {
    slug: "tagline-generator",
    h1: "Tagline Generator",
    title: "Tagline Generator Tool",
    description: "Generate short tagline ideas for products, brands, and pages.",
    keyword: "tagline generator",
    intro: "Use this tagline generator when you need a short line for a product, brand, or page.",
    howTo: ["Enter a seed word.", "Generate taglines.", "Pick the one that fits best."],
    useCases: ["Write brand copy.", "Fill hero sections.", "Test short messaging."],
    whyUseful: ["It gives you quick messaging options.", "The results are short and easy to edit.", "It is useful for copy drafts."],
    faqs: [{ q: "Can I use them on a homepage?", a: "Yes. They are short enough for hero copy." }, { q: "Can I copy the lines?", a: "Yes. They are ready to paste." }, { q: "Can I generate more options?", a: "Yes. Try a different seed for another set." }],
    related: ["slogan-generator", "headline-generator", "product-name-generator"],
  },
];

export const TOOL_BY_SLUG = Object.fromEntries(
  TOOL_CONFIGS.map((tool) => [tool.slug, tool]),
) as Record<ToolSlug, ToolConfig>;

const TOOL_HUB_BADGES: Record<ToolSlug, string> = {
  "qr-code-generator": "QR",
  "percentage-calculator": "%",
  "age-calculator": "AGE",
  "json-formatter": "{}",
  "password-generator": "KEY",
  "image-resizer": "IMG",
  "text-case-converter": "Aa",
  "username-generator": "@",
  "color-picker-tool": "HEX",
  "time-zone-converter": "TZ",
  "random-number-generator": "RND",
  "random-word-generator": "WORD",
  "lorem-ipsum-generator": "TXT",
  "color-palette-generator": "PAL",
  "font-generator-tool": "FONT",
  "hashtag-generator": "#",
  "slogan-generator": "SLOG",
  "business-name-generator": "NAME",
  "email-generator": "MAIL",
  "uuid-generator": "ID",
  "barcode-generator": "BAR",
  "word-cloud-generator": "CLOUD",
  "title-generator": "TITLE",
  "acronym-generator": "ACR",
  "ascii-art-generator": "ASC",
  "plot-generator": "PLOT",
  "anagram-generator": "ANAG",
  "phone-number-generator": "TEL",
  "random-letter-generator": "LTR",
  "random-animal-generator": "ANM",
  "random-city-generator": "CITY",
  "random-country-generator": "CTRY",
  "fantasy-name-generator": "FNT",
  "superhero-name-generator": "HERO",
  "fake-data-generator": "DATA",
  "secret-santa-generator": "SANTA",
  "bingo-card-generator": "BINGO",
  "truth-table-generator": "LOGIC",
  "rhyming-word-generator": "RHYME",
  "color-scheme-generator": "SCHEME",
  "headline-generator": "HEAD",
  "thesis-statement-generator": "THESIS",
  "restaurant-name-generator": "FOOD",
  "fancy-text-generator": "FANCY",
  "glitch-text-generator": "GLITCH",
  "mla-citation-generator": "MLA",
  "business-niche-generator": "NICHE",
  "product-name-generator": "PROD",
  "startup-idea-generator": "IDEA",
  "story-prompt-generator": "PROMPT",
  "plot-twist-generator": "TWIST",
  "word-mixer-generator": "MIX",
  "sequence-generator": "SEQ",
  "icon-label-generator": "ICON",
  "character-name-generator": "CHAR",
  "team-name-generator": "TEAM",
  "ai-prompt-starter-generator": "AI",
  "tagline-generator": "TAG",
};

const TOOL_HUB_TINTS: Record<ToolSlug, { ring: string; glow: string; badge: string; accent: string }> = {
  "qr-code-generator": {
    ring: "rgba(245,95,42,0.16)",
    glow: "rgba(245,95,42,0.10)",
    badge: "bg-[#f55f2a] text-white",
    accent: "bg-[#f55f2a]",
  },
  "percentage-calculator": {
    ring: "rgba(15,118,110,0.16)",
    glow: "rgba(15,118,110,0.10)",
    badge: "bg-teal-600 text-white",
    accent: "bg-teal-600",
  },
  "age-calculator": {
    ring: "rgba(99,102,241,0.16)",
    glow: "rgba(99,102,241,0.10)",
    badge: "bg-indigo-600 text-white",
    accent: "bg-indigo-600",
  },
  "json-formatter": {
    ring: "rgba(107,114,128,0.18)",
    glow: "rgba(107,114,128,0.10)",
    badge: "bg-neutral-800 text-white",
    accent: "bg-neutral-800",
  },
  "password-generator": {
    ring: "rgba(168,85,247,0.16)",
    glow: "rgba(168,85,247,0.10)",
    badge: "bg-violet-600 text-white",
    accent: "bg-violet-600",
  },
  "image-resizer": {
    ring: "rgba(14,165,233,0.16)",
    glow: "rgba(14,165,233,0.10)",
    badge: "bg-sky-600 text-white",
    accent: "bg-sky-600",
  },
  "text-case-converter": {
    ring: "rgba(202,138,4,0.16)",
    glow: "rgba(202,138,4,0.10)",
    badge: "bg-amber-600 text-white",
    accent: "bg-amber-600",
  },
  "username-generator": {
    ring: "rgba(190,24,93,0.16)",
    glow: "rgba(190,24,93,0.10)",
    badge: "bg-pink-700 text-white",
    accent: "bg-pink-700",
  },
  "color-picker-tool": {
    ring: "rgba(34,197,94,0.16)",
    glow: "rgba(34,197,94,0.10)",
    badge: "bg-emerald-600 text-white",
    accent: "bg-emerald-600",
  },
  "time-zone-converter": {
    ring: "rgba(2,132,199,0.16)",
    glow: "rgba(2,132,199,0.10)",
    badge: "bg-cyan-700 text-white",
    accent: "bg-cyan-700",
  },
  "random-number-generator": {
    ring: "rgba(245,95,42,0.16)",
    glow: "rgba(245,95,42,0.10)",
    badge: "bg-[#f55f2a] text-white",
    accent: "bg-[#f55f2a]",
  },
  "random-word-generator": {
    ring: "rgba(14,165,233,0.16)",
    glow: "rgba(14,165,233,0.10)",
    badge: "bg-sky-600 text-white",
    accent: "bg-sky-600",
  },
  "lorem-ipsum-generator": {
    ring: "rgba(107,114,128,0.18)",
    glow: "rgba(107,114,128,0.10)",
    badge: "bg-neutral-800 text-white",
    accent: "bg-neutral-800",
  },
  "color-palette-generator": {
    ring: "rgba(34,197,94,0.16)",
    glow: "rgba(34,197,94,0.10)",
    badge: "bg-emerald-600 text-white",
    accent: "bg-emerald-600",
  },
  "font-generator-tool": {
    ring: "rgba(202,138,4,0.16)",
    glow: "rgba(202,138,4,0.10)",
    badge: "bg-amber-600 text-white",
    accent: "bg-amber-600",
  },
  "hashtag-generator": {
    ring: "rgba(190,24,93,0.16)",
    glow: "rgba(190,24,93,0.10)",
    badge: "bg-pink-700 text-white",
    accent: "bg-pink-700",
  },
  "slogan-generator": {
    ring: "rgba(99,102,241,0.16)",
    glow: "rgba(99,102,241,0.10)",
    badge: "bg-indigo-600 text-white",
    accent: "bg-indigo-600",
  },
  "business-name-generator": {
    ring: "rgba(245,95,42,0.16)",
    glow: "rgba(245,95,42,0.10)",
    badge: "bg-[#f55f2a] text-white",
    accent: "bg-[#f55f2a]",
  },
  "email-generator": {
    ring: "rgba(107,114,128,0.18)",
    glow: "rgba(107,114,128,0.10)",
    badge: "bg-neutral-800 text-white",
    accent: "bg-neutral-800",
  },
  "uuid-generator": {
    ring: "rgba(34,197,94,0.16)",
    glow: "rgba(34,197,94,0.10)",
    badge: "bg-emerald-600 text-white",
    accent: "bg-emerald-600",
  },
  "barcode-generator": {
    ring: "rgba(168,85,247,0.16)",
    glow: "rgba(168,85,247,0.10)",
    badge: "bg-violet-600 text-white",
    accent: "bg-violet-600",
  },
  "word-cloud-generator": {
    ring: "rgba(202,138,4,0.16)",
    glow: "rgba(202,138,4,0.10)",
    badge: "bg-amber-600 text-white",
    accent: "bg-amber-600",
  },
  "title-generator": {
    ring: "rgba(190,24,93,0.16)",
    glow: "rgba(190,24,93,0.10)",
    badge: "bg-pink-700 text-white",
    accent: "bg-pink-700",
  },
  "acronym-generator": {
    ring: "rgba(99,102,241,0.16)",
    glow: "rgba(99,102,241,0.10)",
    badge: "bg-indigo-600 text-white",
    accent: "bg-indigo-600",
  },
  "ascii-art-generator": {
    ring: "rgba(245,95,42,0.16)",
    glow: "rgba(245,95,42,0.10)",
    badge: "bg-[#f55f2a] text-white",
    accent: "bg-[#f55f2a]",
  },
  "plot-generator": {
    ring: "rgba(14,165,233,0.16)",
    glow: "rgba(14,165,233,0.10)",
    badge: "bg-sky-600 text-white",
    accent: "bg-sky-600",
  },
  "anagram-generator": {
    ring: "rgba(107,114,128,0.18)",
    glow: "rgba(107,114,128,0.10)",
    badge: "bg-neutral-800 text-white",
    accent: "bg-neutral-800",
  },
  "phone-number-generator": {
    ring: "rgba(34,197,94,0.16)",
    glow: "rgba(34,197,94,0.10)",
    badge: "bg-emerald-600 text-white",
    accent: "bg-emerald-600",
  },
  "random-letter-generator": { ring: "rgba(245,95,42,0.16)", glow: "rgba(245,95,42,0.10)", badge: "bg-[#f55f2a] text-white", accent: "bg-[#f55f2a]" },
  "random-animal-generator": { ring: "rgba(14,165,233,0.16)", glow: "rgba(14,165,233,0.10)", badge: "bg-sky-600 text-white", accent: "bg-sky-600" },
  "random-city-generator": { ring: "rgba(107,114,128,0.18)", glow: "rgba(107,114,128,0.10)", badge: "bg-neutral-800 text-white", accent: "bg-neutral-800" },
  "random-country-generator": { ring: "rgba(34,197,94,0.16)", glow: "rgba(34,197,94,0.10)", badge: "bg-emerald-600 text-white", accent: "bg-emerald-600" },
  "fantasy-name-generator": { ring: "rgba(168,85,247,0.16)", glow: "rgba(168,85,247,0.10)", badge: "bg-violet-600 text-white", accent: "bg-violet-600" },
  "superhero-name-generator": { ring: "rgba(99,102,241,0.16)", glow: "rgba(99,102,241,0.10)", badge: "bg-indigo-600 text-white", accent: "bg-indigo-600" },
  "fake-data-generator": { ring: "rgba(202,138,4,0.16)", glow: "rgba(202,138,4,0.10)", badge: "bg-amber-600 text-white", accent: "bg-amber-600" },
  "secret-santa-generator": { ring: "rgba(190,24,93,0.16)", glow: "rgba(190,24,93,0.10)", badge: "bg-pink-700 text-white", accent: "bg-pink-700" },
  "bingo-card-generator": { ring: "rgba(245,95,42,0.16)", glow: "rgba(245,95,42,0.10)", badge: "bg-[#f55f2a] text-white", accent: "bg-[#f55f2a]" },
  "truth-table-generator": { ring: "rgba(14,165,233,0.16)", glow: "rgba(14,165,233,0.10)", badge: "bg-sky-600 text-white", accent: "bg-sky-600" },
  "rhyming-word-generator": { ring: "rgba(107,114,128,0.18)", glow: "rgba(107,114,128,0.10)", badge: "bg-neutral-800 text-white", accent: "bg-neutral-800" },
  "color-scheme-generator": { ring: "rgba(34,197,94,0.16)", glow: "rgba(34,197,94,0.10)", badge: "bg-emerald-600 text-white", accent: "bg-emerald-600" },
  "headline-generator": { ring: "rgba(168,85,247,0.16)", glow: "rgba(168,85,247,0.10)", badge: "bg-violet-600 text-white", accent: "bg-violet-600" },
  "thesis-statement-generator": { ring: "rgba(99,102,241,0.16)", glow: "rgba(99,102,241,0.10)", badge: "bg-indigo-600 text-white", accent: "bg-indigo-600" },
  "restaurant-name-generator": { ring: "rgba(202,138,4,0.16)", glow: "rgba(202,138,4,0.10)", badge: "bg-amber-600 text-white", accent: "bg-amber-600" },
  "fancy-text-generator": { ring: "rgba(190,24,93,0.16)", glow: "rgba(190,24,93,0.10)", badge: "bg-pink-700 text-white", accent: "bg-pink-700" },
  "glitch-text-generator": { ring: "rgba(245,95,42,0.16)", glow: "rgba(245,95,42,0.10)", badge: "bg-[#f55f2a] text-white", accent: "bg-[#f55f2a]" },
  "mla-citation-generator": { ring: "rgba(14,165,233,0.16)", glow: "rgba(14,165,233,0.10)", badge: "bg-sky-600 text-white", accent: "bg-sky-600" },
  "business-niche-generator": { ring: "rgba(107,114,128,0.18)", glow: "rgba(107,114,128,0.10)", badge: "bg-neutral-800 text-white", accent: "bg-neutral-800" },
  "product-name-generator": { ring: "rgba(34,197,94,0.16)", glow: "rgba(34,197,94,0.10)", badge: "bg-emerald-600 text-white", accent: "bg-emerald-600" },
  "startup-idea-generator": { ring: "rgba(168,85,247,0.16)", glow: "rgba(168,85,247,0.10)", badge: "bg-violet-600 text-white", accent: "bg-violet-600" },
  "story-prompt-generator": { ring: "rgba(99,102,241,0.16)", glow: "rgba(99,102,241,0.10)", badge: "bg-indigo-600 text-white", accent: "bg-indigo-600" },
  "plot-twist-generator": { ring: "rgba(202,138,4,0.16)", glow: "rgba(202,138,4,0.10)", badge: "bg-amber-600 text-white", accent: "bg-amber-600" },
  "word-mixer-generator": { ring: "rgba(190,24,93,0.16)", glow: "rgba(190,24,93,0.10)", badge: "bg-pink-700 text-white", accent: "bg-pink-700" },
  "sequence-generator": { ring: "rgba(245,95,42,0.16)", glow: "rgba(245,95,42,0.10)", badge: "bg-[#f55f2a] text-white", accent: "bg-[#f55f2a]" },
  "icon-label-generator": { ring: "rgba(14,165,233,0.16)", glow: "rgba(14,165,233,0.10)", badge: "bg-sky-600 text-white", accent: "bg-sky-600" },
  "character-name-generator": { ring: "rgba(107,114,128,0.18)", glow: "rgba(107,114,128,0.10)", badge: "bg-neutral-800 text-white", accent: "bg-neutral-800" },
  "team-name-generator": { ring: "rgba(34,197,94,0.16)", glow: "rgba(34,197,94,0.10)", badge: "bg-emerald-600 text-white", accent: "bg-emerald-600" },
  "ai-prompt-starter-generator": { ring: "rgba(168,85,247,0.16)", glow: "rgba(168,85,247,0.10)", badge: "bg-violet-600 text-white", accent: "bg-violet-600" },
  "tagline-generator": { ring: "rgba(99,102,241,0.16)", glow: "rgba(99,102,241,0.10)", badge: "bg-indigo-600 text-white", accent: "bg-indigo-600" },
};

export const TOOL_HUB_ITEMS = TOOL_CONFIGS.map((tool) => ({
  label: tool.title,
  href: `/tools/${tool.slug}`,
  description: tool.description,
  keyword: tool.keyword,
  badge: TOOL_HUB_BADGES[tool.slug],
  tint: TOOL_HUB_TINTS[tool.slug],
}));
